### ISSUE TITLE
bug: self-hosting langfuse can't log any trace

### ISSUE THREAD

**Issue by 9620300** [langfuse/langfuse#3407]
### Describe the bug

I try to log my langchain app sessions using a selfhosted languse. This langfuse is deployed using a docker compose in a server which does not have any internet connection. The langfuse app is deployed successfully,  I can get access to it on web, however, it can't log any langchain session. The same version works well on my local laptop. 

### To reproduce

deploy a self-hosting in a server which does not have any outgoing internet connection.

### SDK and container versions

v 2.78.0

### Additional information

The information I got at the backend is 

LangFuse     | 2024-09-19T05:39:32.928Z error   ❌ tRPC failed on public.checkUpdate: Failed to fetch or json parse the latest releases Failed to fetch or json parse the latest release
sLangFuse     | TRPCError: Failed to fetch or json parse the latest releases
LangFuse     |     at /app/web/.next/server/pages/api/trpc/[trpc].js:406:4188
LangFuse     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
LangFuse     |     at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)
LangFuse     |     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
LangFuse     |     at async file:///app/node_modules/.pnpm/@baselime+trpc-opentelemetry-middleware@0.1.2_@opentelemetry+api@1.8.0_@trpc+server@10.45.2/node_modules/@baselime/trpc-open
telemetry-middleware/dist/index.js:43:22LangFuse     |     at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
LangFuse     |     at async resolve (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
LangFuse     |     at async inputToProcedureCall (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
LangFuse     |     at async Promise.all (index 0)
LangFuse     |     at async resolveHTTPResponse (file:///app/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:182:37)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Thanks for sharing. This should be fixed (basically just fetches the latest Langfuse release version). This should however have no impact on traces as it is just a frontend route. Can you share more details to help me understand why traces might not work in your case? (Implementation code, environment)

**Comment by 9620300** [comment]
I used this docker compose script to run langfuse:

services:
  langfuse-db:
    image: harbor.fzzqft.com/datascience/postgres:16-alpine
    container_name: LangFuse-DB
    hostname: langfuse-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./langfuse-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure:5

  langfuse:
    image: harbor.fzzqft.com/datascience/langfuse/langfuse:240912
    container_name: LangFuse
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - langfuse-db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@langfuse-db:5432/${POSTGRES_DB}?sslmode=disable
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SALT: ${SALT}
      LANGFUSE_CSP_ENFORCE_HTTPS: true
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: false
      TELEMETRY_ENABLED: false
      AUTH_DISABLE_SIGNUP: ${AUTH_DISABLE_SIGNUP}
      LANGFUSE_INIT_USER_EMAIL: user@example.com
      LANGFUSE_INIT_USER_PASSWORD: user12345678
      LANGFUSE_INIT_ORG_ID: my-org
      LANGFUSE_INIT_PROJECT_ID: my-project
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: lf_pk_1234567890

the .env file in the same path is like below:

POSTGRES_USER='user'
POSTGRES_PASSWORD='pass'
POSTGRES_DB='langfuse'
NEXTAUTH_SECRET=aOlY0UgIitolkrZUWoWyVRwuo2BpUPKB/t2l2ufbXSw=
SALT=VBQk4V98zZ8L8xwpvI696Ixv88D5QfrciLU4fx/C4VQ=
AUTH_DISABLE_SIGNUP=false
NEXT_PUBLIC_LANGFUSE_CLOUD_REGION='DEV'

The system starting up messages are below:

[+] Running 2/0
 ✔ Container LangFuse-DB  Created                                                                                                                                                 0.0s 
 ✔ Container LangFuse     Created                                                                                                                                                 0.0s 
Attaching to LangFuse, LangFuse-DB
LangFuse-DB  | 
LangFuse-DB  | PostgreSQL Database directory appears to contain a database; Skipping initialization
LangFuse-DB  | 
LangFuse-DB  | 2024-09-19 08:20:02.360 UTC [1] LOG:  starting PostgreSQL 16.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
LangFuse-DB  | 2024-09-19 08:20:02.360 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
LangFuse-DB  | 2024-09-19 08:20:02.360 UTC [1] LOG:  listening on IPv6 address "::", port 5432
LangFuse-DB  | 2024-09-19 08:20:02.360 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
LangFuse-DB  | 2024-09-19 08:20:02.373 UTC [29] LOG:  database system was shut down at 2024-09-19 08:19:59 UTC
LangFuse-DB  | 2024-09-19 08:20:02.384 UTC [1] LOG:  database system is ready to accept connections
LangFuse     | Script executed successfully.
LangFuse     | Prisma schema loaded from packages/shared/prisma/schema.prisma
LangFuse     | Datasource "db": PostgreSQL database "langfuse", schema "public" at "langfuse-db:5432"
LangFuse     | 
LangFuse     | 234 migrations found in prisma/migrations
LangFuse     | 
LangFuse     | 
LangFuse     | No pending migrations to apply.
LangFuse     |   ▲ Next.js 14.2.6
LangFuse     |   - Local:        http://493fe8c46130:3000
LangFuse     |   - Network:      http://172.19.0.3:3000
LangFuse     | 
LangFuse     |  ✓ Starting...
LangFuse     |  ✓ Ready in 2.4s


The service is hosted behind a NG load balancer in a local network, the url is something like http://langfuse.xxx.com, the web access works well, I can login and play around without getting any error message.

the langchain code is nothing special, I just followed the samples on langfuse official doc, some key lines like:
 
langfuse_handler = CallbackHandler()
config = {"callbacks": [langfuse_handler]}
...
async for chunk in graph.astream(inputs, config, stream_mode="values"):
...
the public key, secret key and host are all set per the above system. 

The code actually works on my laptop

**Comment by 9620300** [comment]
NEXT_PUBLIC_LANGFUSE_CLOUD_REGION='DEV' -- this line was added after I found I didn't get any trace, I read the source code and found this might stop the system from querying for the updates... it actually doesn't resolve anything

**Comment by marcklingen** [comment]
Thanks for sharing

Please only use envs documented here: https://langfuse.com/docs/deployment/self-host

**Comment by marcklingen** [comment]
Thanks for sharing that this works locally, can you run langfuse_handler.auth_check() in prod?

**Comment by 9620300** [comment]
> Thanks for sharing that this works locally, can you run langfuse_handler.auth_check() in prod?

Thanks for help. How to run it? just put langfuse_handler.auth_check() behind langfuse_handler = CallbackHandler() ?

**Comment by 9620300** [comment]
I think I found the reason, I just changed the host to http://localhost:3000 instead of http://langfuse.xxx.com/, it works now, I seems to be a network issue.

Thanks for your help!

**Comment by marcklingen** [comment]
thanks for confirming!
